#!/usr/bin/env bash

ENVIRONMENTS=(
    "Development|development/setup_dev.sh|setup_dev_environment"
    "Reading|reading/setup_reading.sh|setup_reading_environment"
    "Browser|internet/browser/setup_browser.sh|setup_browser_environment"
    "Multimedia|multimedia/setup_multimedia.sh|setup_multimedia_environment"
    "Security|security/setup_security.sh|setup_security_environment"
    "Productivity|productivity/setup_productivity.sh|setup_productivity_environment"
)
