FROM fedora-minimal:latest

RUN echo "install_weak_deps=False" >> /etc/dnf/dnf.conf

# Manually add Mullvad repo file
RUN curl --tlsv1.3 -o /etc/yum.repos.d/mullvad.repo https://repository.mullvad.net/rpm/stable/mullvad.repo 

# Install essential packages
RUN microdnf update -y && \
    microdnf install -y \
        libavcodec-free mesa-dri-drivers pipewire mesa-libEGL mullvad-browser && \ 
    microdnf clean all

# Upgrade packages
ARG CACHE_BUST=1
RUN microdnf update -y && microdnf upgrade -y && microdnf clean all

# Create non-root user
ARG UID=1000
ARG GID=1000

RUN groupadd -g "$GID" user \
    && useradd -m -u "$UID" -g "$GID" user

RUN printf '#!/bin/sh\necho "bwrap: setting up uid map: Permission denied" >&2\nexit 1\n' > /usr/bin/bwrap && chmod +x /usr/bin/bwrap

USER user
ENV HOME=/home/user
WORKDIR /home/user
