FROM alpine:latest

# Install essential packages
RUN apk add mesa-dri-gallium foliate font-carlito

# Upgrade packages
ARG CACHE_BUST=1
RUN apk upgrade

RUN fc-cache -fv

# Create non-root user
ARG UID=1000
ARG GID=1000

RUN addgroup -g "$GID" user 2>/dev/null || true && \
    adduser -u "$UID" -g "$GID" -D -S -h /home/user user 

USER user
WORKDIR /home/user
