--use-fake-device-for-media-stream
--disable-reading-from-canvas
--component-updater=disable-pings
--disable-breakpad
--propagate-iph-for-testing
--disable-crash-reporter
--no-default-browser-check
--disable-remote-fonts
--no-pings
--js-flags=--jitless
--disable-webgl
--disable-3d-apis
--ozone-platform=wayland
--extension-content-verification=enforce_strict
--extensions-install-verification=enforce_strict
--enable-features=ClearCrossSiteCrossBrowsingContextGroupWindowName,CertificateTransparencyAskBeforeEnabling,IsolateSandboxedIframes:grouping/per-document,LocalNetworkAccessChecksWebRTC,PartitionAllocWithAdvancedChecks:enabled-processes/all-processes,OriginKeyedProcessesByDefault,HstsTopLevelNavigationsOnly,PartitionConnectionsByNetworkIsolationKey,ScopeMemoryCachePerContext,SplitCacheByIncludeCredentials,SplitCacheByNetworkIsolationKey,SplitCodeCacheByNetworkIsolationKey,ReduceAcceptLanguage,StrictOriginIsolation
--disable-features=AimEnabled,LensStandalone,StarterPackExpansion,AutofillServerCommunication,InterestFeedV2,NTPPopularSitesBakedInContent,Journeys,MediaDrmPreprovisioning,OptimizationHints,OptimizationHintsFetchingSRP,BrowsingTopics,BrowsingTopicsDocumentAPI,BrowsingTopicsParameters,PrivacySandboxSettings4,Reporting,CrashReporting,DocumentReporting,AllowSwiftShaderFallback,AllowSoftwareGLFallbackDueToCrash,TabHoverCardImages,WebGPUBlobCache,WebGPUService
