FROM fedora-minimal:latest

RUN echo "install_weak_deps=False" >> /etc/dnf/dnf.conf

RUN dnf install -y https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm   

# Install essential packages
RUN microdnf update -y && microdnf install -y unrar && microdnf clean all

# Upgrade packages
ARG CACHE_BUST=1
RUN microdnf update -y && microdnf upgrade -y && microdnf clean all

# Create non-root user
ARG UID=1000
ARG GID=1000

RUN groupadd -g "$GID" user \
    && useradd -m -u "$UID" -g "$GID" user

USER user
ENV HOME=/home/user
WORKDIR /home/user
